name: pull last version on server
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd plsergent.github.io && git pull
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSWORD }}
        privateKey: ${{ secrets.KEY }}