name: pull last version on server
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd plsergent.github.io
          git config --global user.email "papa.louis59@gmail.com"
          git config --global user.name "Pierre-Louis Sergent"
          git pull
          cd ..
          caddy stop
          caddy start &
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSWORD }}
        privateKey: ${{ secrets.KEY }}
